### ISSUE TITLE
Getting the completely wrong video 

### ISSUE THREAD

**Issue by joshholly** [Inside4ndroid/AIO-StreamSource#3]
So I was trying to watch The Curse, season 1 episode 1 from flixhq ,and the HLS file it got me was not even for that TV show. It gave me an HLS file for an 80s movie that I am not sure what it was. But it was not at all the TV show I was looking for at all.  It wasn't even a TV show , it was a completely different movie.  I noticed it did this on a few other TV shows as well. Movies it seems to work okay.

/vidsrc?id=114655&type=tv&provider=flixhq&s=1&e=1 to reproduce this error.

**Comment by joshholly** [comment]
Found the issue! There's another TV show called "The Curse" and it just happened to grab the first one. Would be cool if you could maybe also search by release date?

**Comment by kissyfaceDev** [comment]
> Found the issue! There's another TV show called "The Curse" and it just happened to grab the first one. Would be cool if you could maybe also search by release date?

did you find a work around?
