### ISSUE TITLE
Providers unable to fetch 

### ISSUE THREAD

**Issue by kissyfaceDev** [Inside4ndroid/AIO-StreamSource#7]
im trying to get the details of futurama like this :3000/vidsrc?id=615&s=6&e=1&provider=flixhq  , it keeps crashing and i get the message contact the developer for help

**Comment by harisnaeemofficial** [comment]
Same Error, I think this Repo is Dead

**Comment by Inside4ndroid** [comment]
Sorry I have been rather busy with other projects I will update this as soon as possible.
